trigger:
- master

variables:
- group: CustodianCoreCI

jobs:

- job: 'CustodianDockerBuild'
  displayName: 'Docker Build'
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - checkout: self
    fetchDepth: 1
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.8
      architecture: 'x64'
  # bin directory is in .dockerignore
  - script: |
      python3 -m pip install --upgrade pip
      pip3 install docker click pytest pyyaml six
  # build a docker image and sanity test
  - script: |
      python3 tools/dev/dockerpkg.py build -t build --verbose --test -i cli
