name: "Docker Build"
on:
  push:
    branches:
      - master
      - main
    tags:
      # todo: update for 1.0
      - 0.*
jobs:
  Publish:
    permissions:
      id-token: write
    strategy:
      matrix:
        image:
          - c7n
          - c7n-org
          - mailer
          - policystream
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.image }} build and push
        uses: ./.github/composites/docker-build-push
        env:
          HUB_USER: c7nbuild
          HUB_TOKEN: ${{ secrets.DOCKER_CI_HUB_TOKEN }}
        with:
          name: ${{ matrix.image }}
          push: true
          platforms: linux/arm64,linux/amd64
